### ISSUE TITLE
malloc(): memory corruption error

### ISSUE THREAD

**Issue by pkuwalter** [coolerzxw/GridGraph#2]
Hi Coolerzxw,

I'm very glad to GridGraph. I download the code to run on a ThinkPad T450 with 8G memory machine, but when I preprocessing the data it shows the following error:
`Error in ./bin/preprocess: malloc(): memory corruption: 0x00007f8c98000960`
Can you help me to fix this?

Thank you.

**Comment by coolerzxw** [comment]
Hi. Can you provide more detailed information, such as the input data, the parameters for preprocessing, the OS, the compiler, and the detailed place where this error happens?

**Comment by pkuwalter** [comment]
OK. The detailed information is as follow:
I run the code under ubuntu 16.04 with gcc 4.8.5. I got this error when I run pagerank with Amazon0601. The detailed information is posted as below:
`walter@walter-ubuntu:~/GridGraph$ sudo ./bin/preprocess -i ../data/txt/Amazon0601.txt -o ../data/txt/Amazon -v 403394 -p 4 -t 0`
`[sudo] walter 的密码： `
`vertices = 403394, edges = 5081082`
`*** Error in `./bin/preprocess'`: malloc(): memory corruption: 0x00007fd420000960 ***`
`======= Backtrace: =========`
`/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7fd43dcb0725]`
`/lib/x86_64-linux-gnu/libc.so.6(+0x819be)[0x7fd43dcba9be]`
`/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fd43dcbc5a4]`
`/lib/x86_64-linux-gnu/libc.so.6(vasprintf+0x22)[0x7fd43dcaf632]`
`/lib/x86_64-linux-gnu/libc.so.6(asprintf+0x87)[0x7fd43dc8ea07]`
`/lib/x86_64-linux-gnu/libc.so.6(+0x2db2f)[0x7fd43dc66b2f]`
`/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7fd43dc66c82]`
`./bin/preprocess[0x40274b]`
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbac6f)[0x7fd43e4f0c6f]`
`/lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa)[0x7fd43e0096fa]`
`/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fd43dd3fb5d]`
`======= Memory map: ========`
`00400000-00406000 r-xp 00000000 08:08 3015254 `                           `/home/walter/GridGraph/bin/preprocess`
`00606000-00607000 r--p 00006000 08:08 3015254  `                          `/home/walter/GridGraph/bin/preprocess`
`00607000-00608000 rw-p 00007000 08:08 3015254    `                        `/home/walter/GridGraph/bin/preprocess`
`01ec4000-01ef6000 rw-p 00000000 00:00 0                                  [heap]`
`7fd410000000-7fd411822000 rw-p 00000000 00:00 0 `
`7fd411822000-7fd414000000 ---p 00000000 00:00 0 `
`7fd414000000-7fd414021000 rw-p 00000000 00:00 0`
`7fd414021000-7fd418000000 ---p 00000000 00:00 0 `
`7fd418000000-7fd419822000 rw-p 00000000 00:00 0 `
`7fd419822000-7fd41c000000 ---p 00000000 00:00 0 `
`7fd420000000-7fd421822000 rw-p 00000000 00:00 0 `
`7fd421822000-7fd424000000 ---p 00000000 00:00 0 `
`7fd428000000-7fd429822000 rw-p 00000000 00:00 0 `
`7fd429822000-7fd42c000000 ---p 00000000 00:00 0 `
`7fd42f91c000-7fd42f91d000 ---p 00000000 00:00 0 `
`7fd42f91d000-7fd43011d000 rw-p 00000000 00:00 0 `
`7fd43011d000-7fd43011e000 ---p 00000000 00:00 0 `
`7fd43011e000-7fd43091e000 rw-p 00000000 00:00 0 `
`7fd43091e000-7fd43091f000 ---p 00000000 00:00 0 `
`7fd43091f000-7fd43111f000 rw-p 00000000 00:00 0 `
`7fd43111f000-7fd431120000 ---p 00000000 00:00 0 `
`7fd431120000-7fd43d930000 rw-p 00000000 00:00 0 `
`7fd43d930000-7fd43da38000 r-xp 00000000 08:03 136186                     /lib/x86_64-linux-gnu/libm-2.23.so`
`7fd43da38000-7fd43dc37000 ---p 00108000 08:03 136186                     /lib/x86_64-linux-gnu/libm-2.23.so`
`7fd43dc37000-7fd43dc38000 r--p 00107000 08:03 136186                     /lib/x86_64-linux-gnu/libm-2.23.so`
`7fd43dc38000-7fd43dc39000 rw-p 00108000 08:03 136186                     /lib/x86_64-linux-gnu/libm-2.23.so`
`7fd43dc39000-7fd43ddf9000 r-xp 00000000 08:03 136116                     /lib/x86_64-linux-gnu/libc-2.23.so`
`7fd43ddf9000-7fd43dff8000 ---p 001c0000 08:03 136116                     /lib/x86_64-linux-gnu/libc-2.23.so`
`7fd43dff8000-7fd43dffc000 r--p 001bf000 08:03 136116                     /lib/x86_64-linux-gnu/libc-2.23.so`
`7fd43dffc000-7fd43dffe000 rw-p 001c3000 08:03 136116                     /lib/x86_64-linux-gnu/libc-2.23.so`
`7fd43dffe000-7fd43e002000 rw-p 00000000 00:00 0 `
`7fd43e002000-7fd43e01a000 r-xp 00000000 08:03 136262                     /lib/x86_64-linux-gnu/libpthread-2.23.so`
`7fd43e01a000-7fd43e219000 ---p 00018000 08:03 136262                     /lib/x86_64-linux-gnu/libpthread-2.23.so`
`7fd43e219000-7fd43e21a000 r--p 00017000 08:03 136262                     /lib/x86_64-linux-gnu/libpthread-2.23.so`
`7fd43e21a000-7fd43e21b000 rw-p 00018000 08:03 136262                     /lib/x86_64-linux-gnu/libpthread-2.23.so`
`7fd43e21b000-7fd43e21f000 rw-p 00000000 00:00 0 `
`7fd43e21f000-7fd43e235000 r-xp 00000000 08:03 131077                     /lib/x86_64-linux-gnu/libgcc_s.so.1`
`7fd43e235000-7fd43e434000 ---p 00016000 08:03 131077                     /lib/x86_64-linux-gnu/libgcc_s.so.1`
`7fd43e434000-7fd43e435000 r--p 00015000 08:03 131077                     /lib/x86_64-linux-gnu/libgcc_s.so.1`
`7fd43e435000-7fd43e436000 rw-p 00016000 08:03 131077                     /lib/x86_64-linux-gnu/libgcc_s.so.1`
`7fd43e436000-7fd43e5ad000 r-xp 00000000 08:03 1966571                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22`
`7fd43e5ad000-7fd43e7ad000 ---p 00177000 08:03 1966571                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22`
`7fd43e7ad000-7fd43e7b7000 r--p 00177000 08:03 1966571                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22`
`7fd43e7b7000-7fd43e7b9000 rw-p 00181000 08:03 1966571                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22`
`7fd43e7b9000-7fd43e7bd000 rw-p 00000000 00:00 0 `
`7fd43e7bd000-7fd43e7e3000 r-xp 00000000 08:03 136088                     /lib/x86_64-linux-gnu/ld-2.23.so`
`7fd43e9bc000-7fd43e9c2000 rw-p 00000000 00:00 0 `
`7fd43e9df000-7fd43e9e2000 rw-p 00000000 00:00 0 `
`7fd43e9e2000-7fd43e9e3000 r--p 00025000 08:03 136088                     /lib/x86_64-linux-gnu/ld-2.23.so`
`7fd43e9e3000-7fd43e9e4000 rw-p 00026000 08:03 136088                     /lib/x86_64-linux-gnu/ld-2.23.so`
`7fd43e9e4000-7fd43e9e5000 rw-p 00000000 00:00 0 `
`7ffdd864f000-7ffdd8670000 rw-p 00000000 00:00 0                          [stack]`
`7ffdd8775000-7ffdd8777000 r--p 00000000 00:00 0                          [vvar]`
`7ffdd8777000-7ffdd8779000 r-xp 00000000 00:00 0                          [vdso]`
`ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]`
`已放弃 (核心已转储)`

**Comment by coolerzxw** [comment]
Okay I see the problem. You need to convert the input file from the text format into the binary form (as shown in https://github.com/coolerzxw/GridGraph#preprocessing). You may try the following code for the conversion task:
```
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

int main(int argc, char ** argv) {
	FILE * fin = fopen(argv[1], "r");
	FILE * fout = fopen(argv[2], "wb");
	char * line = new char [1024];
	size_t line_length;
	ssize_t read_length;
	int max_vid = 0;
	while ((read_length = getline(&line, &line_length, fin)) != -1) {
		if (line[0]=='#') continue;
		int src, dst;
		assert(sscanf(line, "%d %d", &src, &dst)==2);
		fwrite(&src, sizeof(int), 1, fout);
		fwrite(&dst, sizeof(int), 1, fout);
		if (src > max_vid) max_vid = src;
		if (dst > max_vid) max_vid = dst;
	}
	fclose(fin);
	fclose(fout);
	printf("|V|=%d\n", max_vid + 1);
}
```

**Comment by pkuwalter** [comment]
I see well. I have run GridGraph successfully. Thank you very much. I once used the X-stream to transfer the data file, it is also the binary file
